FROM python:3.10-slim

# Java es necesario para Spark
RUN apt-get update && apt-get install -y \
    default-jdk wget curl && \
    rm -rf /var/lib/apt/lists/*

# Instalar PySpark y Jupyter
RUN pip install pyspark==3.5.0 jupyter notebook

WORKDIR /workspace

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", \
     "--no-browser", "--allow-root", "--NotebookApp.token=''"]